@host = http://localhost:8089
@projectName = superadmin_personal
@username =
@password =
@access_token =

### Get OAuth2 Token
POST {{host}}/uat/sso/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dWk6dWltYW4=

grant_type=password&username={{username}}&password={{password}}

> {% client.global.set("access_token", response.body.access_token); %}

### Start new launch
POST {{host}}/api/v2/{{projectName}}/launch
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "New Launch from API",
  "startTime": {{$isoTimestamp}},
  "description": "This is a new launch created via API"
}

> {% client.global.set("launchUuid", response.body.id); %}


### Finish launch
PUT {{host}}/api/v2/{{projectName}}/launch/{{launchUuid}}/finish
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "endTime": "2024-06-10T12:00:00.000Z",
  "status": "PASSED"
}

### Get launches
GET {{host}}/api/v1/{{projectName}}/launch
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get old launch format
GET {{host}}/api/v1/{{projectName}}/launch/uuid/64a5d4b3-3c3a-448a-8537-104406deb0dc
Authorization: Bearer {{access_token}}

### Get new launch format
GET {{host}}/api/v1/{{projectName}}/launch/uuid/64a5d4b3-3c3a-448a-8537-104406deb0dc
Authorization: Bearer {{access_token}}
Accept: application/x.reportportal.launch.v2+json
